### ISSUE TITLE
RedisServer.open() does not resolve after successful start

### ISSUE THREAD

**Issue by sa-linetco** [BrandonZacharie/node-redis-server#12] opened 2018-06-04 15:51 UTC
Version information
-----
```
~$ redis-server --version
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=1bc80a08306a3efd

~$ cat redis-server/package.json
"version": "1.2.0"
```

Observed behaviour
-----
When I try to start a Redis-Server instance with the configuration
```
port 6381
bind 0.0.0.0
```
I am getting the following output:
```
3105:C 30 May 17:46:28.529 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
3105:C 30 May 17:46:28.529 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=3105, just started
3105:C 30 May 17:46:28.529 # Configuration loaded
3105:M 30 May 17:46:28.529 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
3105:M 30 May 17:46:28.529 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
3105:M 30 May 17:46:28.529 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
3105:M 30 May 17:46:28.529 * Running mode=standalone, port=6381.
3105:M 30 May 17:46:28.529 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
3105:M 30 May 17:46:28.529 # Server initialized
3105:M 30 May 17:46:28.529 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
3105:M 30 May 17:46:28.529 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
3105:M 30 May 17:46:28.530 * Ready to accept connections

```

Expected behaviour
-----
The promise returned by `RedisServer.open()` should have been resolved because the server started successfully.

Problem analysis
-----
The last line `3105:M 30 May 17:46:28.530 * Ready to accept connections` indicates that the server successfully started, though the Promise will not resolve. This is because the regular expression defined in RedisServer.js:47 and executed in RedisServer.js:134 will match on the line `3105:M 30 May 17:46:28.529 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.`.

Workaround
-----
I changed my configuration to
```
port 6382
bind 0.0.0.0
maxclients 100
```
so that the error will not occur.

Possible fix
-----
Match a more specific error instead of only `error` in the regular expression. E.g. `fatal.*error`.

**Comment by sa-linetco** [comment] 2018-06-05 07:58
Somehwhat related: #10

**Comment by BrandonZacharie** [comment] 2018-06-05 16:31
Thanks for the detailed report; it really helps. I also believe this is related to #10. I see 2 problems here:

- promises not resolving
- faulty error detection

The regular expression for matching errors is liberal because there are a great many of errors that can occur. Too many to write individual expressions for. With that said, even when falsely detecting an error, it should still resolve the promise. Unfortunately, I cannot reproduce these issues on my local machines nor on Travis CI so I'd like to start with replicating your environment. What OS have you? Where did you source the Redis binary (i.e. Homebrew, MacPorts, Apt, etc.)? Any other info related to your setup may help.

**Comment by sa-linetco** [comment] 2018-06-06 09:20
Thank you for your quick reply. Here is the information you asked for.

OS:
```
~$ cat /etc/issue
Ubuntu 18.04 LTS \n \l
```
redis-server installed via apt:
```
~$ dpkg -l | grep redis-server
ii  redis-server                               5:4.0.9-1                           amd64        Persistent key-value database with network interface
```

If you still happen not to be able to reproduce the behaviour I'm happy to provide more information.

**Comment by BrandonZacharie** [comment] 2018-06-06 15:52
@sa-linetco I created a Docker container for Ubuntu 18.04 LTS, installed Redis via Apt, and have run `redis-server` as a non-root user. I am still unable to reproduce the permission error as seen in your logs. However, I took a shot at simulating the log message in a test (see 6d83712). Give it a try. If any problem remains, I'll reopen this issue.

**Comment by sa-linetco** [comment] 2018-06-07 08:30
The issue still persists on my system. The workaround to ignore that specific warning would work if the message
```
Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
```
would be received lone in the `parseData` method.

On my system I receive all the output of the redis server instance at once. So the warning regexp matches, the function returns null as of "no match" and the remainder of the redis output goes lost.

I added some output to the `parseData` method.
```
  static parseData(string) {
    console.log('==========');
    console.log('parsing data');
    console.log('----------');
    console.log(string);
    console.log('----------');
    const matches = regExp.terminalMessage.exec(string);
    console.log('matches:', matches);
    const warningMatches = regExp.warningMessage.test(string);
    console.log('----------');
    console.log('warning matches:', warningMatches);
    ...
```

which results in the following output:
```
==========
parsing data
----------
5443:C 07 Jun 08:14:15.149 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
5443:C 07 Jun 08:14:15.149 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=5443, just started
5443:C 07 Jun 08:14:15.149 # Configuration loaded
5443:M 07 Jun 08:14:15.149 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
5443:M 07 Jun 08:14:15.149 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
5443:M 07 Jun 08:14:15.149 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
5443:M 07 Jun 08:14:15.149 * Running mode=standalone, port=6381.
5443:M 07 Jun 08:14:15.149 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
5443:M 07 Jun 08:14:15.149 # Server initialized
5443:M 07 Jun 08:14:15.149 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
5443:M 07 Jun 08:14:15.149 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
5443:M 07 Jun 08:14:15.149 * Ready to accept connections

----------
matches: [ 'can\'t',
  index: 382,
  input: '5443:C 07 Jun 08:14:15.149 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo\n5443:C 07 Jun 08:14:15.149 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=5443, just started\n5443:C 07 Jun 08:14:15.149 # Configuration loaded\n5443:M 07 Jun 08:14:15.149 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.\n5443:M 07 Jun 08:14:15.149 # Server can\'t set maximum open files to 10032 because of OS error: Operation not permitted.\n5443:M 07 Jun 08:14:15.149 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase \'ulimit -n\'.\n5443:M 07 Jun 08:14:15.149 * Running mode=standalone, port=6381.\n5443:M 07 Jun 08:14:15.149 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.\n5443:M 07 Jun 08:14:15.149 # Server initialized\n5443:M 07 Jun 08:14:15.149 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add \'vm.overcommit_memory = 1\' to /etc/sysctl.conf and then reboot or run the command \'sysctl vm.overcommit_memory=1\' for this to take effect.\n5443:M 07 Jun 08:14:15.149 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command \'echo never > /sys/kernel/mm/transparent_hugepage/enabled\' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.\n5443:M 07 Jun 08:14:15.149 * Ready to accept connections\n' ]
----------
warning matches: true
```

I opened a pull request to handle startup, error and warning messages separately and check for the startup message first.

**Comment by sa-linetco** [comment] 2018-06-07 08:30
https://github.com/BrandonZacharie/node-redis-server/pull/13

**Comment by BrandonZacharie** [comment] 2018-06-08 00:01
Thanks for the update. I think I fully understand the issue now. As you mentioned earlier, the problem is that failure is checked _before_ success. It should definitely be the opposite because non-fatal errors, like this one, may occur. "Ready to accept connections" only ever appears when Redis is good to go. The simplest solution is to add precedence to the terminal regular expressions giving priority to the success case. That should work for this and any other non-fatal error.

**Comment by BrandonZacharie** [comment] 2018-06-08 00:50
[1.2.1](/BrandonZacharie/node-redis-server/releases/tag/1.2.1) is published. If you still have this problem, I'll reopen the issue.

**Comment by sa-linetco** [comment] 2018-06-08 09:53
The issue is still not solved 100%.

The workaround you added in https://github.com/BrandonZacharie/node-redis-server/commit/6d83712099d044d94ff119464ccf69d205b6bb9d and reverted in https://github.com/BrandonZacharie/node-redis-server/commit/ce0b05994c8dc6cbce9396f486786b94a2654d51 is still needed in this case.

I tried to open a redis server instance again and this time I did not receive the whole output at once, but split into two parts.

```
parseData(string) {
    console.log(string);
}
```

```
19822:C 08 Jun 11:50:34.930 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
19822:C 08 Jun 11:50:34.930 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=19822, just started
19822:C 08 Jun 11:50:34.930 # Configuration loaded
19822:M 08 Jun 11:50:34.930 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
19822:M 08 Jun 11:50:34.930 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
19822:M 08 Jun 11:50:34.930 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
```

This leads to the precedence you added not matching on the successful startup message as it is not included in the first part of the output.

**Comment by BrandonZacharie** [comment] 2018-06-08 16:59
I see that now. The patch I reverted had a problem also. It would result in any fatal errors being ignored after handling the “Server can’t open...” error. I’ll refactor to add recursive parsing to handle that case.

**Comment by sa-linetco** [comment] 2018-06-11 06:18
What about line by line parsing?

**Comment by sa-linetco** [comment] 2018-06-11 15:51
That solution sounds good, I think the possibility of a stdout chunk being separated in a line is pretty small.

If we ever run into that issue we might need to add a chunk collector which only feeds full lines into the `parseData` method.

**Closed** 2018-06-12 20:08 UTC
Labels: bug

**Comment by BrandonZacharie** [comment] 2018-06-12 20:11
[1.2.2](/BrandonZacharie/node-redis-server/releases/tag/1.2.2) is published. If you still have this problem, I'll reopen the issue.
