### ISSUE TITLE
Basic Example does not working

### ISSUE THREAD

**Issue by mcolombo22** [BrandonZacharie/node-redis-server#6] opened 2017-02-07 17:53 UTC
I´m trying to create a simply redis server and start with the "[Basic Example](https://www.npmjs.com/package/redis-server#basic-example)" but when i run it the following exception is throw

events.js:142
throw er; // Unhandled 'error' event
^

Error: spawn redis-server ENOENT
at exports._errnoException (util.js:856:11)
at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
at onErrorNT (internal/child_process.js:345:16)
at nextTickCallbackWith2Args (node.js:455:9)
at process._tickCallback (node.js:369:17)
at Function.Module.runMain (module.js:433:11)
at startup (node.js:141:18)
at node.js:977:3

I tried to run with the RunKit and receive the same error:
https://runkit.com/589a067aa5c2fc00155ea0df/589a067aa5c2fc00155ea0e0

Could you help me?

**Comment by BrandonZacharie** [comment] 2017-02-07 19:45
You must have a Redis server binary (`redis-server`) available and I don't think RunKit has one. 

`ENONT` stands for **E**rror **NO ENT**ry (No such file or directory). That only occurs in this module when `RedisServer.open` attempts to spawn a child process and the given Redis server binary (`redis-server` by default) cannot be found in path. However, you may provide a path to a binary in configuration.

```JavaScript
const server = new RedisServer({
  bin: '/path/to/redis-server'
});
```

**Comment by BrandonZacharie** [comment] 2017-02-20 19:49
Are you able to get this working locally after installing Redis?

**Comment by BrandonZacharie** [comment] 2017-02-20 19:53
I'm closing this as a duplicate of #2. If you have any further issues, I'll reopen.

**Closed by BrandonZacharie** 2017-02-20 19:53 UTC
Labels: duplicate, question
